//! The shared rule, shuffle, hash and leave-text vectors (PLAN.md § Contract
//! fixtures), generated by contract-fixtures/tools/ from an independent
//! reference and never from this code.

use serde_json::{json, Value};
use uuid::Uuid;

use super::order::{questions_hash, reset_seed, shuffle, SplitMix64};
use super::rows::Progression;
use super::rules::{self, Grade, Opts};
use super::sim::{Op, SimCascade};
use crate::leave::leave_value_text;

fn fixture(name: &str) -> Value {
    let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../contract-fixtures/cascade").join(name);
    serde_json::from_slice(&std::fs::read(p).unwrap()).unwrap()
}

fn u64s(v: &Value) -> u64 {
    // Every 64-bit value is decimal text, never a JSON number.
    v.as_str().expect("decimal text").parse().unwrap()
}

fn uuid(v: &Value) -> Uuid {
    v.as_str().unwrap().parse().unwrap()
}

fn prog(v: &Value) -> Progression {
    match v.as_str().unwrap() {
        "ladder" => Progression::Ladder,
        _ => Progression::Drill,
    }
}

fn op_of(o: &Value) -> Op {
    let q = || uuid(&o["quiz"]);
    let att = || o["attempt"].as_u64().unwrap() as u32;
    let aseed = || u64s(&o["attempt_seed"]);
    let opt_prog = || o.get("progression").map(prog);
    let opt_size = || o.get("segment_size").map(|v| v.as_i64().unwrap());
    let opt_alpha = || o.get("require_alphabetical").map(|v| v.as_bool().unwrap());
    match o["type"].as_str().unwrap() {
        "grade" => Op::Grade {
            quiz: q(),
            attempt: att(),
            attempt_seed: aseed(),
            question_idx: o["question_idx"].as_u64().unwrap() as u32,
            grade: if o["grade"] == "correct" { Grade::Correct } else { Grade::Missed },
        },
        "move_cursor" => Op::MoveCursor { quiz: q(), attempt: att(), attempt_seed: aseed(), position: o["position"].as_u64().unwrap() as u32 },
        "finish" => Op::Finish {
            quiz: q(),
            attempt: att(),
            attempt_seed: aseed(),
            shuffle_seed: u64s(&o["shuffle_seed"]),
            new_quiz_id: uuid(&o["new_quiz_id"]),
        },
        "finish_segment" => Op::FinishSegment {
            quiz: q(),
            attempt: att(),
            attempt_seed: aseed(),
            segment_end: o["segment_end"].as_u64().unwrap() as u32,
            shuffle_seed: u64s(&o["shuffle_seed"]),
            new_quiz_id: uuid(&o["new_quiz_id"]),
        },
        "restore_quiz" => Op::RestoreQuiz { quiz: q(), shuffle_seed: u64s(&o["shuffle_seed"]) },
        "trash_cascade" => Op::TrashCascade,
        "restore_cascade" => Op::RestoreCascade,
        "purge_quiz" => Op::PurgeQuiz { quiz: q() },
        "purge_cascade" => Op::PurgeCascade,
        "set_cascade_options" => Op::SetCascadeOptions { segment_size: opt_size(), progression: opt_prog(), require_alphabetical: opt_alpha() },
        "set_quiz_options" => Op::SetQuizOptions { quiz: q(), segment_size: opt_size(), progression: opt_prog(), require_alphabetical: opt_alpha() },
        t => panic!("unknown op {t}"),
    }
}

fn prog_str(p: Progression) -> &'static str {
    match p {
        Progression::Ladder => "ladder",
        Progression::Drill => "drill",
    }
}

fn origin_str(o: super::rows::Origin) -> &'static str {
    use super::rows::Origin::*;
    match o {
        Source => "source",
        ClearReplacement => "clear_replacement",
        DrillReplacement => "drill_replacement",
        Descent => "descent",
        Segment => "segment",
    }
}

fn snapshot(c: &SimCascade) -> Value {
    let quizzes: Vec<Value> = c
        .quizzes
        .values()
        .map(|q| {
            let s = &q.state;
            json!({
                "id": q.id.to_string(),
                "level": s.level,
                "status": if s.active { "active" } else { "cleared" },
                "origin": origin_str(s.origin),
                "origin_quiz_id": q.origin_quiz_id.map(|u| u.to_string()),
                "origin_attempt": q.origin_attempt,
                "origin_segment_end": q.origin_segment_end,
                "segment_chain": s.segment_chain,
                "segment_size": s.opts.segment_size,
                "progression": prog_str(s.opts.progression),
                "require_alphabetical": s.opts.require_alphabetical,
                "attempt": s.attempt,
                "shuffle_seed": s.seed.to_string(),
                "question_count": s.question_count,
                "questions_hash": questions_hash(&q.questions).to_string(),
                "questions": q.questions,
                "correct": q.correct(),
                "missed": q.missed(),
                "cursor": s.cursor,
                "run_start": s.run_start,
                "next_boundary": if s.active { rules::next_boundary(s) } else { None },
                "run_indicator": if s.active { rules::run_indicator(s).map(|r| r.to_string()) } else { None },
            })
        })
        .collect();
    json!({
        "cascade": {
            "depth": c.state.depth,
            "peak_depth": c.state.peak_depth,
            "attempts_since_completion": c.state.attempts_since_completion,
            "completions": c.completions,
            "trashed": c.state.trashed,
            "purged": c.purged,
            "segment_size": c.state.opts.segment_size,
            "progression": prog_str(c.state.opts.progression),
            "require_alphabetical": c.state.opts.require_alphabetical,
        },
        "quizzes": quizzes,
    })
}

#[test]
fn every_rule_vector() {
    let f = fixture("rules.json");
    let vectors = f["vectors"].as_array().unwrap();
    assert!(vectors.len() >= 29);
    for v in vectors {
        let name = v["name"].as_str().unwrap();
        let s = &v["setup"];
        let mut c = SimCascade::new(
            s["clear_threshold"].as_u64().unwrap() as u32,
            Opts {
                segment_size: s["segment_size"].as_u64().unwrap() as u32,
                progression: prog(&s["progression"]),
                require_alphabetical: s["require_alphabetical"].as_bool().unwrap(),
            },
            s["question_count"].as_u64().unwrap() as u32,
            uuid(&s["source_quiz_id"]),
            u64s(&s["source_seed"]),
        );
        for (i, step) in v["steps"].as_array().unwrap().iter().enumerate() {
            let r = c.apply(&op_of(&step["op"]));
            let want = &step["result"];
            match r {
                Ok(a) => {
                    assert_eq!(want["status"], "applied", "{name} step {i}: {:?}", step["op"]);
                    assert_eq!(a.outcome.as_deref(), want["outcome"].as_str(), "{name} step {i} outcome");
                    assert_eq!(
                        a.new_quiz_question_count.map(u64::from),
                        want["new_quiz_question_count"].as_u64(),
                        "{name} step {i} count"
                    );
                    assert_eq!(
                        a.new_quiz_questions_hash,
                        want.get("new_quiz_questions_hash").map(u64s),
                        "{name} step {i} hash"
                    );
                    let completion = want.get("completion").map(|c| {
                        (c["levels"].as_u64().unwrap() as u32, c["attempts"].as_u64().unwrap() as u32)
                    });
                    assert_eq!(a.completion, completion, "{name} step {i} completion");
                }
                Err(reason) => {
                    assert_eq!(want["status"], "rejected", "{name} step {i}: rejected {reason:?}");
                    assert_eq!(want["reason"], reason.as_str(), "{name} step {i}");
                }
            }
            if let Some(state) = step.get("state") {
                assert_eq!(&snapshot(&c), state, "{name} step {i} state");
            }
        }
        if name.starts_with("the ceil") {
            // PQ-011: 8 quizzes made by the attempt, 7 of them segment chains.
            let made = c.quizzes.values().filter(|q| q.origin_quiz_id.is_some()).count();
            assert_eq!(made, 8);
        }
    }
}

#[test]
fn shuffle_vectors() {
    let f = fixture("shuffle.json");
    for s in f["splitmix64"].as_array().unwrap() {
        let mut r = SplitMix64::new(u64s(&s["seed"]));
        let got: Vec<String> = (0..5).map(|_| r.next_u64().to_string()).collect();
        let want: Vec<String> = s["outputs"].as_array().unwrap().iter().map(|x| x.as_str().unwrap().to_owned()).collect();
        assert_eq!(got, want);
    }
    for s in f["shuffles"].as_array().unwrap() {
        let idx: Vec<u32> = s["idx"].as_array().unwrap().iter().map(|x| x.as_u64().unwrap() as u32).collect();
        let want: Vec<u32> = s["positions"].as_array().unwrap().iter().map(|x| x.as_u64().unwrap() as u32).collect();
        assert_eq!(shuffle(&idx, u64s(&s["seed"])), want, "seed {}", s["seed"]);
    }
    for s in f["reset_seeds"].as_array().unwrap() {
        assert_eq!(reset_seed(u64s(&s["seed"])), u64s(&s["reset_seed"]));
    }
}

#[test]
fn hash_vectors() {
    let f = fixture("hash.json");
    for h in f["hashes"].as_array().unwrap() {
        let idx: Vec<u32> = match h.get("idx_range") {
            Some(r) => (r[0].as_u64().unwrap() as u32..r[1].as_u64().unwrap() as u32).collect(),
            None => h["idx"].as_array().unwrap().iter().map(|x| x.as_u64().unwrap() as u32).collect(),
        };
        let got = questions_hash(&idx);
        assert_eq!(got.to_string(), h["hash"].as_str().unwrap(), "{}", h["name"]);
        // The stored i64 is not the value: a hash above 2^63 reads back negative.
        if h["above_2_63"] == true {
            assert!(super::order::to_i64(got) < 0);
        }
    }
}

#[test]
fn leave_text_vectors() {
    let f = fixture("leave_text.json");
    for c in f["cases"].as_array().unwrap() {
        let v = c["value"].as_f64().unwrap();
        let d = c["decimals"].as_u64().unwrap() as u32;
        assert_eq!(leave_value_text(v, d, true), c["screen"].as_str().unwrap(), "{v} at {d}");
        assert_eq!(leave_value_text(v, d, false), c["export"].as_str().unwrap(), "{v} at {d}");
    }
}

/// The cascade stack stays valid (PLAN.md § Unit tests → Property tests): the
/// active levels are exactly 1..depth, Level 1 is the Source quiz, every
/// level's questions come from the Source quiz, run_start never exceeds the
/// cursor, a chain is never segmented and stays Drill, origin_segment_end is
/// unique per parent attempt, and peak_depth ≥ depth.
pub(crate) fn check_invariants(c: &SimCascade) {
    if c.purged {
        return;
    }
    let mut levels: Vec<u32> = c.quizzes.values().filter(|q| q.state.active).map(|q| q.state.level).collect();
    levels.sort_unstable();
    assert_eq!(levels, (1..=c.state.depth).collect::<Vec<_>>(), "active levels are 1..depth");
    assert!(c.state.peak_depth >= c.state.depth);
    let source = c.quizzes.values().find(|q| q.state.origin == super::rows::Origin::Source).expect("a Source quiz");
    assert!(source.state.active && source.state.level == 1);
    let mut segments = std::collections::HashSet::new();
    for q in c.quizzes.values() {
        let s = &q.state;
        assert!(q.questions.iter().all(|i| *i < source.state.question_count));
        assert!(s.run_start <= s.cursor && s.cursor < s.question_count);
        if s.segment_chain {
            assert_eq!(s.opts.segment_size, 0);
            assert_eq!(s.opts.progression, Progression::Drill);
        }
        if s.origin == super::rows::Origin::Segment {
            assert!(s.segment_chain);
            assert!(segments.insert((q.origin_quiz_id, q.origin_attempt, q.origin_segment_end)), "one per run");
        }
        assert_eq!(q.questions.len() as u32, s.question_count);
    }
}

#[test]
fn the_shared_random_sequences() {
    let f = fixture("random.json");
    for v in f["vectors"].as_array().unwrap() {
        let name = v["name"].as_str().unwrap();
        let s = &v["setup"];
        let mut c = SimCascade::new(
            s["clear_threshold"].as_u64().unwrap() as u32,
            Opts {
                segment_size: s["segment_size"].as_u64().unwrap() as u32,
                progression: prog(&s["progression"]),
                require_alphabetical: s["require_alphabetical"].as_bool().unwrap(),
            },
            s["question_count"].as_u64().unwrap() as u32,
            uuid(&s["source_quiz_id"]),
            u64s(&s["source_seed"]),
        );
        for (i, step) in v["steps"].as_array().unwrap().iter().enumerate() {
            let r = c.apply(&op_of(&step["op"]));
            let want = &step["result"];
            match r {
                Ok(a) => {
                    assert_eq!(want["status"], "applied", "{name} step {i}");
                    assert_eq!(a.outcome.as_deref(), want["outcome"].as_str(), "{name} step {i}");
                    assert_eq!(a.new_quiz_questions_hash, want.get("new_quiz_questions_hash").map(u64s), "{name} step {i}");
                }
                Err(reason) => assert_eq!(want["reason"], reason.as_str(), "{name} step {i}"),
            }
            check_invariants(&c);
            if let Some(state) = step.get("state") {
                assert_eq!(&snapshot(&c), state, "{name} step {i} state");
            }
        }
    }
}

mod props {
    use proptest::prelude::*;

    use super::*;

    /// Plays a cascade from a list of random choices, choosing legal
    /// operations from the current state, and checks the invariants after each.
    fn drive(choices: &[u32], count: u32, size: u32, drill: bool) {
        let source = Uuid::from_u128(1);
        let opts = Opts {
            segment_size: size,
            progression: if drill { Progression::Drill } else { Progression::Ladder },
            require_alphabetical: false,
        };
        let mut c = SimCascade::new(80, opts, count, source, 0x1234_5678_9ABC_DEF0);
        let mut next_id = 2u128;
        for (k, &ch) in choices.iter().enumerate() {
            let seed = u64::from(ch).wrapping_mul(0x9E37_79B9_7F4A_7C15) ^ k as u64;
            let op = match ch % 10 {
                _ if c.state.trashed => Op::RestoreCascade,
                0..=5 => {
                    let Some(q) = c.deepest().cloned() else { continue };
                    let pos = q.positions();
                    let end = rules::next_boundary(&q.state).unwrap_or(q.state.question_count);
                    let run_done = (q.state.run_start..end).all(|p| q.grades.contains_key(&pos[p as usize]));
                    next_id += 1;
                    if run_done && q.state.cursor + 1 == end {
                        if end < q.state.question_count {
                            Op::FinishSegment { quiz: q.id, attempt: q.state.attempt, attempt_seed: q.state.seed, segment_end: end, shuffle_seed: seed, new_quiz_id: Uuid::from_u128(next_id) }
                        } else {
                            Op::Finish { quiz: q.id, attempt: q.state.attempt, attempt_seed: q.state.seed, shuffle_seed: seed, new_quiz_id: Uuid::from_u128(next_id) }
                        }
                    } else if !q.grades.contains_key(&pos[q.state.cursor as usize]) {
                        let grade = if ch % 3 == 0 { Grade::Missed } else { Grade::Correct };
                        Op::Grade { quiz: q.id, attempt: q.state.attempt, attempt_seed: q.state.seed, question_idx: pos[q.state.cursor as usize], grade }
                    } else {
                        Op::MoveCursor { quiz: q.id, attempt: q.state.attempt, attempt_seed: q.state.seed, position: q.state.cursor + 1 }
                    }
                }
                6 => {
                    let Some(q) = c.deepest().cloned() else { continue };
                    Op::SetQuizOptions { quiz: q.id, segment_size: Some([0, 5, 6, 300_000][(ch as usize / 10) % 4]), progression: None, require_alphabetical: None }
                }
                7 => {
                    let cleared: Vec<Uuid> = c.quizzes.values().filter(|q| !q.state.active).map(|q| q.id).collect();
                    if cleared.is_empty() {
                        continue;
                    }
                    Op::RestoreQuiz { quiz: cleared[(ch as usize / 10) % cleared.len()], shuffle_seed: seed }
                }
                8 => Op::TrashCascade,
                _ => Op::SetCascadeOptions { segment_size: Some([0, 5, 9][(ch as usize / 10) % 3]), progression: None, require_alphabetical: None },
            };
            let _ = c.apply(&op);
            check_invariants(&c);
            for q in c.quizzes.values() {
                // Every quiz's rows hash to its questions_hash.
                assert_eq!(questions_hash(&q.questions), questions_hash(&shuffle(&q.questions, q.state.seed)));
            }
        }
    }

    proptest! {
        #![proptest_config(ProptestConfig::with_cases(300))]
        #[test]
        fn the_cascade_stack_stays_valid(choices in prop::collection::vec(any::<u32>(), 50..400), count in 5u32..60, size in prop::sample::select(vec![0u32, 5, 7, 10, 100]), drill in any::<bool>()) {
            drive(&choices, count, size, drill);
        }
    }
}
