// PLAN.md § Contract fixtures: the shared rule, shuffle, hash and leave-text
// vectors, generated by contract-fixtures/tools/ from an independent reference.
import { describe, expect, it } from 'vitest';
import rules from '../../../../contract-fixtures/cascade/rules.json';
import shuffles from '../../../../contract-fixtures/cascade/shuffle.json';
import hashes from '../../../../contract-fixtures/cascade/hash.json';
import leaves from '../../../../contract-fixtures/cascade/leave_text.json';
import { fromI64, questionsHash, resetSeed, shuffle, SplitMix64, toI64 } from './order';
import { leaveValueText } from './leave';
import { nextBoundary, Rejected, runIndicator, runIndicatorText, type Progression } from './rules';
import { SimCascade, type Op } from './sim';

type Json = Record<string, unknown>;

function opOf(o: Json): Op {
	const big = (k: string) => BigInt(o[k] as string);
	const t = o.type as string;
	const base = { ...o } as Json;
	for (const k of ['attempt_seed', 'shuffle_seed']) if (k in o) base[k] = big(k);
	return { ...base, type: t } as unknown as Op;
}

function snapshot(c: SimCascade) {
	const quizzes = [...c.quizzes.values()]
		.sort((a, b) => (a.id < b.id ? -1 : 1))
		.map((q) => {
			const s = q.state;
			let cor = 0,
				mis = 0;
			for (const g of q.grades.values()) (g === 'correct' ? cor++ : mis++);
			const ri = s.active ? runIndicator(s) : null;
			return {
				id: q.id,
				level: s.level,
				status: s.active ? 'active' : 'cleared',
				origin: s.origin,
				origin_quiz_id: q.origin_quiz_id,
				origin_attempt: q.origin_attempt,
				origin_segment_end: q.origin_segment_end,
				segment_chain: s.segment_chain,
				segment_size: s.opts.segment_size,
				progression: s.opts.progression,
				require_alphabetical: s.opts.require_alphabetical,
				attempt: s.attempt,
				shuffle_seed: s.seed.toString(),
				question_count: s.question_count,
				questions_hash: questionsHash(q.questions).toString(),
				questions: q.questions,
				correct: cor,
				missed: mis,
				cursor: s.cursor,
				run_start: s.run_start,
				next_boundary: s.active ? nextBoundary(s) : null,
				run_indicator: ri ? runIndicatorText(ri) : null
			};
		});
	return {
		cascade: {
			depth: c.state.depth,
			peak_depth: c.state.peak_depth,
			attempts_since_completion: c.state.attempts_since_completion,
			completions: c.completions,
			trashed: c.state.trashed,
			purged: c.purged,
			segment_size: c.state.opts.segment_size,
			progression: c.state.opts.progression,
			require_alphabetical: c.state.opts.require_alphabetical
		},
		quizzes
	};
}

describe('the rule vectors', () => {
	for (const v of rules.vectors as unknown as Json[]) {
		it(v.name as string, () => {
			const s = v.setup as Json;
			const c = new SimCascade(
				s.clear_threshold as number,
				{
					segment_size: s.segment_size as number,
					progression: s.progression as Progression,
					require_alphabetical: s.require_alphabetical as boolean
				},
				s.question_count as number,
				s.source_quiz_id as string,
				BigInt(s.source_seed as string)
			);
			(v.steps as Json[]).forEach((step, i) => {
				const want = step.result as Json;
				let got: Json;
				try {
					const a = c.apply(opOf(step.op as Json));
					got = { status: 'applied' };
					if (a.outcome !== undefined) got.outcome = a.outcome;
					if (a.new_quiz_question_count !== undefined) got.new_quiz_question_count = a.new_quiz_question_count;
					if (a.new_quiz_questions_hash !== undefined) got.new_quiz_questions_hash = a.new_quiz_questions_hash.toString();
					if (a.completion) got.completion = a.completion;
				} catch (e) {
					if (!(e instanceof Rejected)) throw e;
					got = { status: 'rejected', reason: e.reason };
				}
				const expected = { ...want };
				delete expected.attempt; // the attempt record, checked through state
				expect(got, `${v.name} step ${i}`).toEqual(expected);
				if (step.state) expect(snapshot(c), `${v.name} step ${i} state`).toEqual(step.state);
			});
			if ((v.name as string).startsWith('the ceil')) {
				// PQ-011: 8 quizzes made by the attempt, 7 of them segment chains.
				expect([...c.quizzes.values()].filter((q) => q.origin_quiz_id !== null)).toHaveLength(8);
			}
		});
	}
});

describe('shuffles, hashes and leave text', () => {
	it('matches splitmix64.c', () => {
		for (const s of shuffles.splitmix64) {
			const r = new SplitMix64(BigInt(s.seed));
			expect(Array.from({ length: 5 }, () => r.next().toString())).toEqual(s.outputs);
		}
	});
	it('shuffles', () => {
		for (const s of shuffles.shuffles) expect(shuffle(s.idx, BigInt(s.seed))).toEqual(s.positions);
		for (const s of shuffles.reset_seeds) expect(resetSeed(BigInt(s.seed)).toString()).toBe(s.reset_seed);
	});
	it('hashes, as unsigned decimal text', () => {
		for (const h of hashes.hashes as Json[]) {
			const r = h.idx_range as number[] | undefined;
			const idx = r ? Array.from({ length: r[1] - r[0] }, (_, i) => r[0] + i) : (h.idx as number[]);
			const got = questionsHash(idx);
			expect(got.toString(), h.name as string).toBe(h.hash);
			if (h.above_2_63) {
				expect(toI64(got) < 0n).toBe(true);
				expect(fromI64(toI64(got))).toBe(got);
				// A side that parsed it as a JSON number would lose it.
				expect(BigInt(Number(h.hash))).not.toBe(got);
			}
		}
	});
	it('writes leave values', () => {
		for (const c of leaves.cases) {
			expect(leaveValueText(c.value, c.decimals, true), `${c.value} ${c.decimals}`).toBe(c.screen);
			expect(leaveValueText(c.value, c.decimals, false)).toBe(c.export);
		}
	});
});
