#!/usr/bin/env python3
"""Generates contract-fixtures/filters/conditions.json from PLAN.md.

Independent of the Rust and TypeScript code under test (PLAN.md § Contract
fixtures → Contract test): it reads three tables straight out of PLAN.md —
the parameter table under the API's filter JSON (§ API → Catalog and search),
the Filter reference (§ Filters, for labels, the Not column and limits) and
the applicability table (§ Filter applicability by quiz type) — so a filter
parameter cannot be added on one side only and no field name is chosen twice.

Run from the repository root: python3 contract-fixtures/tools/gen_filters.py
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PLAN = (ROOT / "PLAN.md").read_text(encoding="utf-8").splitlines()
OUT = ROOT / "contract-fixtures" / "filters" / "conditions.json"


def table_after(marker: str) -> list:
    """The rows of the first markdown table after the line containing marker."""
    start = next(i for i, l in enumerate(PLAN) if marker in l)
    rows, seen = [], False
    for line in PLAN[start + 1:]:
        if line.startswith("|"):
            seen = True
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if set("".join(cells)) <= set("-: "):
                continue
            rows.append(cells)
        elif seen:
            break
    return rows[1:]  # drop the header


# 1. The type list, in the API's order.
type_line = next(i for i, l in enumerate(PLAN) if l.startswith("`type` is one of "))
type_text = " ".join(PLAN[type_line:type_line + 6])
types = re.findall(r"`([a-z_]+)`", type_text.split("Only the")[0])[1:]  # skip "type"
assert len(types) == 23, types

# 2. Fields per type from the parameter table.
fields = {}
for type_cell, field_cell, _form in table_after("The parameter fields, by type:"):
    names = re.findall(r"`([a-z_]+)`", type_cell)
    fs = re.findall(r"`([a-z_]+)`", field_cell)
    for n in names:
        fields[n] = fs
assert set(fields) == set(types), set(types) ^ set(fields)

# 3. Labels, Not and limits from the Filter reference (rows 1–23 in type order).
reference = table_after("### Filter reference")
labels, negatable, limit = {}, {}, {}
for row, t in zip(reference, types):
    labels[t] = re.sub(r"\*", "", row[1]).split("(")[0].strip()
    negatable[t] = row[3] == "✓"
    limit[t] = "*Limit.*" in row[4]

# 4. Applicability.
by_label = {v: k for k, v in labels.items()}
applies = {t: [] for t in types}
quiz_types = ["anagram", "definition", "leave_value"]
for row in table_after("### Filter applicability by quiz type"):
    names = [n.strip() for n in row[0].split(" / ")]
    if names[-1].endswith(" Match") and len(names) > 1:
        names = [n if n.endswith(" Match") else n + " Match" for n in names]
    for n in names:
        t = by_label[n]
        for q, cell in zip(quiz_types, row[1:4]):
            if cell.startswith("✓"):
                applies[t].append(q)
assert all(applies.values()), applies

# 5. One valid condition per type, and one with an extra field.
SAMPLE = {
    "pattern": "A B .",
    "min": 2,
    "max": 5,
    "lax": True,
    "tiles": "AB",
    "lexicon": "EN-FIX",
    "entries": ["AB", "BA"],
    "part_of_speech": "noun",
    "text": "fish",
}
valid = []
for t in types:
    cond = {"type": t, "negated": False}
    for f in fields[t]:
        cond[f] = SAMPLE[f]
    if t == "leave_value":
        cond["min"], cond["max"] = 10.5, None
    if t == "consists_of":
        cond["min"], cond["max"] = 70, 100
    valid.append({"condition": cond, "text": json.dumps(cond, separators=(",", ":"), ensure_ascii=False)})

fixture = {
    "source": "PLAN.md § API → Catalog and search (parameter table), § Filter reference, "
              "§ Filter applicability by quiz type; generated by contract-fixtures/tools/gen_filters.py",
    "types": [
        {"type": t, "label": labels[t], "fields": fields[t], "negatable": negatable[t],
         "limit": limit[t], "applies_to": applies[t]}
        for t in types
    ],
    "valid": valid,
    "extra_field": {"type": "length", "negated": False, "min": 2, "max": 5, "lax": True},
}
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(fixture, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)}: {len(types)} types")
